### ISSUE TITLE
honor target URL after login

### ISSUE THREAD

**Issue by JesseAA** [Optum/barista#144]
## Reason for Opening:
- [] Propose a feature
- [x] Report a bug 

## Purpose:
When following a project link into Barista, I'm challenged to authenticate, but then I'm just taken to the Barista homepage and not to the URL I requested.

## Caveats:

**Comment by pkn4645** [comment]
When someone shares a deep link that should take you directly to a scan result, it does not work if you need to be authenticated. The login screen intercepts you properly, but after entering username and password you are taken to the Projects default page, not where you originally intended to go.

**Comment by JesseAA** [comment]
right .. that's the 'bug' i'm reporting :)
