### ISSUE TITLE
Get summary license state via API

### ISSUE THREAD

**Issue by JesseAA** [Optum/barista#145]
## Reason for Opening:
- [x] Propose a feature
- [] Report a bug 

## Purpose:
a. API: Given a source code repository URL, return the license state status
b. API: Given a primary application identifier, return a summary license state status representing the license state for every github repo that is associated with that primary application identifier (see caveats)

## Caveats: 
Each github repo would need to have a well-known file that declared the primary application identifier

**Comment by pkn4645** [comment]
notes:

API option 1

1. repository URL + subdirectory (if any) will be required as input to ensure correct project is matched
2. matches will not be case sensitive but does need to be an exact character match
3. if more than one project is identified as a match, most recent successful scan results will be returned
4. license status will be returned as RED, YELLOW or GREEN

API option 2
primary application identifier will return 1 to many license state status results as a JSON array of results
{projectID}, {RED, YELLOW, or GREEN}

**Comment by pkn4645** [comment]
create new unauthenticated api endpoint in STATS controller based on GET /project which will build out the model returned to include current license and security status

**Comment by pkn4645** [comment]
@JesseAA see examples and comments below:

for reference, swagger api docs for unauthenticated stats controller are [here](https://barista.optum.com/api/v1/api-docs/#/Stats/get_stats).  You can restrict fields returned, sort results etc. if needed.

example 1:  retrieve project(s) info including current license and security status by askID - note if more than one project has the same askID value, all will be returned in sequence - this example is for barista and will return 3 projects (web, api, scan)

`curl -X GET "https://barista.optum.com/api/v1/stats?filter%5B%5D=askID%7C%7Ceq%7C%7CUHGWM110-020972" -H "accept: application/jsonclar"`

example 2: retrieve project(s) info including current license and security status by gitURL - note that if gitURL is not unique, all matching projects will be returned in sequence -  this example is for barista main repo and will return 3 projects (web, api, scan)

`curl -X GET "https://barista.optum.com/api/v1/stats?filter%5B%5D=gitUrl%7C%7Ceq%7C%7Chttps%3A%2F%2Fgithub.com%2FOptum%2Fbarista" -H "accept: application/json"`

example 3:  retrieve project(s) info including current license and security status by combination of gitURL and Custom Package Manager Path - note that if the combination is not unique, all matching projects will be returned in sequence - this example is for barista-web and will return a single project

`curl -X GET "https://barista.optum.com/api/v1/stats?filter%5B%5D=gitUrl%7C%7Ceq%7C%7Chttps%3A%2F%2Fgithub.com%2FOptum%2Fbarista&filter%5B%5D=customPackageManagerPath||eq||barista-web/" -H "accept: application/jsonclar"`

**Comment by pkn4645** [comment]
closed by #213
