### ISSUE TITLE
Deep links are lost if user needs to be authenticated

### ISSUE THREAD

**Issue by rolinge** [Optum/barista#148]
## Reason for Opening:
- [] Propose a feature
- [x] Report a bug 

## Purpose:
When someone shares a deep link that should take you directly to a scan result, it does not work if you need to be authenticated.  The login screen intercepts you properly, but after entering username and password you are taken to the Projects default page, not where you originally intended to go.

## Caveats:

**Comment by pkn4645** [comment]
similar to #144

**Comment by pkn4645** [comment]
duplicates #144
