### ISSUE TITLE
Bad link routing to empty page 

### ISSUE THREAD

**Issue by jorden-lee** [Optum/barista#156]
## Reason for Opening:
- [] Report a bug 

## Purpose:
If a user enters a bad link that looks like a possible link such as barista.optum.com/asfsad then the user will be directed to barista.optum.com which is an empty page
## Caveats:

**Comment by sdabhi23** [comment]
Hey @jorden-lee, ideally where should it redirect? To `/home` or `/projects/user`?

**Comment by jorden-lee** [comment]
Ideally it would redirect to /home.

**Comment by sdabhi23** [comment]
We just need to add a wildcard route. I would like to take this up!
