### ISSUE TITLE
Support development on a Linux system

### ISSUE THREAD

**Issue by kevindigo** [Optum/barista#250]
## Reason for Opening:
- [x] Propose a feature

## Purpose:
As a linux user, I would like to be able to install, run, and help develop barista. The current instructions require Docker Desktop, which is not available for linux. 

I'm using Ubuntu 18.04 LTS, which seems like a reasonable level to support. But requiring 20.04 would be OK.

**Comment by pkn4645** [comment]
@rolinge any thoughts on accommodating a Ubuntu based dev environment?

**Comment by woodrbe** [comment]
Yes, Docker Desktop is not available for Linux but the following link (https://hub.docker.com/search?q=&type=edition&offering=community&operating_system=linux) gives directions for using Docker on several Linux distributions. Hopefully, this will allow you to set up your development environment for contributing to Barista.

**Comment by kevindigo** [comment]
Are there instructions anywhere for how to deploy barista in production (as opposed to the dev environment)? Presumably that would support linux, and would be a starting point. All I have found so far is docs for how to set up a dev environment.

I don't know docker well enough to understand the difference between Docker Desktop, Docker Engine, Docker Toolbox, etc. So I can help build out docs, but I am not in a position to figure out how to get it working.

**Comment by pkn4645** [comment]
@kevindigo The short answer is no, as production environments vary wildly from one organization to another.  The developer instructions are intended to provide a quick start for the most common local environments (Mac or Windows) using docker containers to simplify the setup and configuration.  However, for larger scale testing or production, it is normal to install in a modern cloud environment by building these components into containers and deploying individually.  Once the containers are available, production systems usually use a container management system such as Kubernetes or RedHat Openshift to manage them.  If you check the online [documentation here](https://optum.github.io/barista/docs/barista-on-docker) , you will find instructions for building the required docker containers using docker compose.  Beyond that, you will need a better understanding of how to manage docker containers to get Barista up and running outside of the local developer instructions.

**Comment by rolinge** [comment]
Hi Kevin Smith,
If you are interested I can share with you how we deployed production to a
kubernetest system.  We have both openshift and helm templates, but they
need to be customised to each environment.  I'd be happy to meet, contact
me at Randy.Olinger@optimum.com

**Comment by rolinge** [comment]
I think my email address ended up getting auto corrected inadvertently.
The correct one is randy.olinger@optum.com

**Comment by kevindigo** [comment]
Thanks @pkn4645 : That docs link you provided looks like the answer I was hoping for. At a glance, it looks like it describes how to quickly get a demo system up and running. I would suggest linking that page from somewhere in the "getting started" docs. (And apologies if it already is and I just missed it.)

Thanks @rolinge : I'll give the docker docs page a shot, and if I have trouble, or if we get to the point of wanting to really deploy to a more production-like setting, I might reach out to you. 

I still think it would be best for the project to document how to set up a dev system on a linux box. Or for anyone who doesn't want to use docker desktop for some reason. I'm disappointed that this issue was closed, as it indicates to me that the project maintainers disagree.
