### ISSUE TITLE
Documentation example with docker-compose does not seem to work

### ISSUE THREAD

**Issue by nnobelis** [Optum/barista#293]
Hello,

I followed the documentation [here](https://github.com/Optum/barista/blob/master/doc/barista-docs/docs/barista-on-docker.md) to setup a full Barista environment with **docker-compose**.

I start the composition and seed the initial data. Everything works, no error.
Then I connect to the UI with Admin, I get in and....the UI seems broken.

There is no data. I click on Projects->User or Projects->Organisation and nothing happens.
I click Admin->Licenses, nothing happens.
I click on Admin->System Configuration, nothing happens.
and so on....

There is no error in Browser Console, 
I tried `docker-compose logs barista-api`,  `docker-compose logs barista-web` and  `docker-compose logs barista-scan`, there seems to be no error.

Is this docker compose documentation still actual ? If yes, do you have a clue what goes wrong ?

Linux Debian 10
Docker version 19.03.13
Docker-compose version 1.27.4
Browser Firefox ESR and Google Chrome

**Comment by nnobelis** [comment]
For info, when I follow this [tutorial](https://optum.github.io/barista/docs/local-dev-environment), I have the same behaviour : nothing happens in UI.

**Comment by rolinge** [comment]
hi there.  I will take a look and see if I can validate the system.  
When you say no data, do you mean blank white screen?  Or just that there is no data showing up?
Have you attempted to register a project yet?

**Comment by rolinge** [comment]
OK, I have to apologize but you seem to have stumbled on an old set of instructions that are not valid, something we need to clean up.  In order to make it easier, we now host pre-built images for someone to use, and the install is much easier.  The updated instructions are in the [docker-compose folder README](https://github.com/Optum/barista/blob/master/docker-compose/README.md).  I will run a test this evening to ensure that those instructions lead to a working system.  It is possible that a bug snuck in.

**Comment by rolinge** [comment]
@nnobelis Thanks for pointing this out.  I have replicated your error on my local home machine and will enter a bug so this can be fixed.  In the mean time I checkout out version 3.1.0 of the system from git and built it, and it worked.  i pushed those images to the docker hub, so if you are still interested, just change the barista-web image tag in the docker-compose.yaml file from the word "compose" to the word "3.1".  (line 18)

    image: optumopensource/barista-webi:3.1

I'm testing this work-around now,  and it seems to work well.  If you want, you can enter the 3.1 tag onto all three modules in the docker-compose.yaml file (barista-web, barista-scan, and barista-api) and all three will be at a consistent version, but that is not completely necessary.

Something else I noticed is that the first time, it is best to first start the database server, wait about 15 seconds, then start the rest of the systems.   Like so

```
$ docker-compose down -v   # delete everything, reset the database
$ docker-compose up -d database redis
$ sleep 30    # pause, let the database create
$ docker-compose up -d    # start the rest of it
$ docker-compose logs -f    #watch the logs to see when barista-scan is finished initializing, it takes a few minutes
```

I hope this workaround resolves your issue and you have a chance to test.  
Let me know if this still does not work, I'd be happy to help.

**Comment by rolinge** [comment]
@nnobelis we found the problem that was introduced and have corrected it and tested on our own private deploy.  No need for any workarounds now, please try and deploy.  
Again, thanks for testing, we appreciate the time.

**Comment by nnobelis** [comment]
Thanks a lot for your support. I will try your fix.

**Comment by pkn4645** [comment]
I believe this is corrected now - @nnobelis please let us know if you still experience the issue.  thanks
