### ISSUE TITLE
DB error when setting up local env

### ISSUE THREAD

**Issue by nnobelis** [Optum/barista#309]
Hello,

I followed this [tutorial](https://github.com/Optum/barista/blob/master/doc/barista-docs/docs/local-dev-environment.md).

Unfortunately, step 9 was failing with the following error : database "barista-dev" does not exist.

So I connected with **pgadmin** to the server and I found out that the database was named "barista-". I renamed it to "barista-dev" and the command `yarn db:reset` is now successful.

Linux Debian 10
Docker version 19.03.13
Docker-compose version 1.27.4
Browser Firefox ESR and Google Chrome

**Comment by pkn4645** [comment]
Hi @nnobelis - thanks for finding the issue and reporting it.  We will put it in our backlog to get corrected.

**Comment by pkn4645** [comment]
@woodrbe didn't we already correct this?  If so can you link to the appropriate PR and close?  thanks...

**Comment by pkn4645** [comment]
corrected per @woodrbe via #317
