### ISSUE TITLE
Copyright html pages

### ISSUE THREAD

**Issue by woodrbe** [Optum/barista#60]
Autogenerate copyright html pages for scans

**Comment by pkn4645** [comment]
potentially use clearlydefined.io api to create notice file on the fly

https://api.clearlydefined.io/api-docs/

**Comment by pkn4645** [comment]
idea - potentially pull all license files into a folder for the project - to be checked into GitHub

**Comment by pkn4645** [comment]
this tool may be helpful as part of the overall process

https://reuse.readthedocs.io/en/stable/

**Comment by pkn4645** [comment]
idea for implementation - https://github.com/oss-review-toolkit/ort
