### ISSUE TITLE
Executing Docker Gives Error

### ISSUE THREAD

**Issue by zorianix** [Optum/barista#83]

**Comment by zorianix** [comment]
npm ERR! code EEXIST
npm ERR! syscall symlink
npm ERR! path ../lib/node_modules/yarn/bin/yarn.js
npm ERR! dest /usr/local/bin/yarn
npm ERR! errno -17
npm ERR! EEXIST: file already exists, symlink '../lib/node_modules/yarn/bin/yarn.js' -> '/usr/local/bin/yarn'
npm ERR! File exists: /usr/local/bin/yarn
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/app/.npm/_logs/2020-04-20T03_29_38_271Z-debug.log
ERROR: Service 'barista-api' failed to build: The command '/bin/sh -c npm config ls -l && npm install -g  yarn yarnrc' returned a non-zero code: 239

**Comment by zorianix** [comment]
I have tried removing the file , but it doesnt work 


I have freshly installed ubuntu 18 LTS with latest ver of docker 19

**Comment by zorianix** [comment]
docker-compose version 1.17.1, build unknown

**Comment by rolinge** [comment]
Hi @zorianix  

Can you run a fresh "docker-compose build" and post the entire log?  Maybe upgrade first (see below)   We have never seen that error before, wondering which point in the build it was failing at.  I assume that barista-base and barista-scanbase each have built already.  It looks like the "npm install -g yarn yarn" command failed.

I don't see how you could remove the file as it should be building fresh in docker each time.  Removing the file at the OS level would not change anything.

I built a script to do the install on a cloud image, but have not posted it as it is not finished.  You are welcome to try it out, command by command, on your fresh Ubuntu server.  Let me know.  I use CentOS, so the Ubuntu version of the script is not well tested.

If you want to upgrade docker-compose on the Ubuntu image, we use 1.25.  Here are the commands to download and upgrade.

```
  sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose \
       && sudo chmod 755 /usr/local/bin/docker-compose
```
make sure you use /usr/local/bin/docker-compose, not the 1.17.1 version you have.

**Comment by woodrbe** [comment]
@zorianix,

This issue has been resolved with the latest PR to master.

**Comment by rolinge** [comment]
@zorianix, please remove previouslu built docker images and rebuild.
docker rmi barista-base:compose barista-scanbase:compose  barista-scan:compose barista-web:compose barista-api:compose

docker-compose build
